# Dictionary

Dictionary adalah tipe data collection yang tidak terurut dari nilai unik yang disimpan dalam pasangan (key dan value). Dictionary Python mewakili pemetaan antara key dan value. Dengan kata sederhana, dictionary Python dapat menyimpan pasangan key dan value. Setiap key terhubung ke value tertentu. Setelah disimpan dalam dictionary, kita dapat memperoleh value tersebut hanya dengan menggunakan kuncinya.

<img src="img/dictionary.jpeg">

## Karakteristik Dictionary
- <strong>Tidak Terurut (Unordered)</strong>: Item dalam dictionary disimpan tanpa nilai indeks, yang biasanya berupa rentang angka. Mereka disimpan sebagai pasangan key-value, di mana key berfungsi sebagai indeks dan tidak memiliki urutan tertentu.

- <strong>Unik (Unique)</strong>: Setiap nilai memiliki key; key dalam dictionary harus unik. Jika kita menyimpan nilai dengan key yang sudah ada, maka nilai terbaru akan menggantikan nilai yang lama.

- <strong>Mutable (Dapat Diubah)</strong>: dictionary adalah koleksi yang dapat diubah, yang berarti kita dapat menambah atau menghapus item setelah dibuat.

## Membuat Dictionary
Ada cara untuk membuat dictionary dalam Python:
- <strong>Menggunakan Kurung Kurawal `{ }`</strong>
- <strong>Menggunakan Konstruktor `dict()`</strong>

### Menggunakan Kurung Kurawal `{ }`
Dictionary dibuat dengan memasukkan pasangan Key: Value yang dipisahkan koma di dalam kurung kurawal `{ }`. Tanda titik dua : digunakan untuk memisahkan key dan value dalam pasangan.

In [2]:
person = {
    "Name": "Mahdy", 
    "Country": "Indonesia", 
    "Telephone": 62822
}
print(person)  # Output: {'Name': 'Mahdy', 'Country': 'Indonesia', 'Telephone': 62822}
print(type(person))  # Output: <class 'dict'>

{'Name': 'Mahdy', 'Country': 'Indonesia', 'Telephone': 62822}
<class 'dict'>


### Menggunakan Konstruktor `dict()`
Dictionary dapat dibuat dengan memanggil konstruktor `dict()` dan memberikan pasangan Key: Item di dalam tanda kurung.

In [4]:
person = dict({"Name": "Mahdy", "Country": "Indonesia", "Telephone": 62822})
print(person)  # Output: {'Name': 'Mahdy', 'Country': 'Indonesia', 'Telephone': 62822}
print(type(person))  # Output: <class 'dict'>

{'Name': 'Mahdy', 'Country': 'Indonesia', 'Telephone': 62822}
<class 'dict'>


## Dictionary Kosong (Empty Dictionary)
Ketkia kita membuat dictionary tanpa ada elemen di dalam kurung kurawal, maka kita akan mendapatkan dictionary kosong.

In [5]:
# Membuat kamus kosong
emptydict = {}
print(type(emptydict))  # Output: <class 'dict'>


<class 'dict'>


## Mengakses Elemen dalam Kamus
Ada dua cara untuk mengakses elemen dalam dictionary di Python:
- <strong>Mengambil Value Menggunakan Nama Key</strong>: Kita dapat mengakses value dengan menggunakan nama key di dalam kurung siku `[ ]`.
- <strong>Mengambil Value dengan Menggunakan Metode `get()`</strong>: Kita dapat mendapatkan value dengan mengirimkan nama key sebagai parameter ke metode `get()` dari dictionary.


In [7]:
# Membuat kamus bernama person
person = {"Name": "Mahdy", "Country": "Indonesia", "Telephone": 62822}


print(person['Name'])  # Output: Mahdy


print(person.get('Telephone'))  # Output: 62822


Mahdy
62822


## Mengambil Semua Key dan Valuee dari Dictionary
Kita dapat menggunakan beberapa metode dictionary untuk mengambil semua key dan value sekaligus. Berikut adalah penjelasan mengenai metode yang dapat digunakan untuk tujuan ini:
- <strong>`keys()`</strong> : Mengembalikan daftar semua kunci yang ada dalam kamus.
- <strong>`values()`</strong> : Mengembalikan daftar semua nilai yang ada dalam kamus.
- <strong>`items()`</strong> : Mengembalikan semua item yang ada dalam kamus. Setiap item akan berada dalam bentuk tuple sebagai pasangan kunci-nilai.

In [9]:
# Membuat kamus bernama person
person = {"name": "Mahdy", "country": "Indonesia", "telephone": 1178}

# Mengambil semua kunci
print(person.keys())  # Output: dict_keys(['name', 'country', 'telephone'])
print(type(person.keys()))  # Output: <class 'dict_keys'>

# Mengambil semua nilai
print(person.values())  # Output: dict_values(['Mahdy', 'Indonesia', 1178])
print(type(person.values()))  # Output: <class 'dict_values'>

# Mengambil semua pasangan kunci-nilai
print(person.items())  # Output: dict_items([('name', 'Mahdy'), ('country', 'Indonesia'), ('telephone', 1178)])
print(type(person.items()))  # Output: <class 'dict_items'>


dict_keys(['name', 'country', 'telephone'])
<class 'dict_keys'>
dict_values(['Mahdy', 'Indonesia', 1178])
<class 'dict_values'>
dict_items([('name', 'Mahdy'), ('country', 'Indonesia'), ('telephone', 1178)])
<class 'dict_items'>


## Iterating Dictionary
Kita dapat mengiterasi melalui sebuah kamus menggunakan loop for dan mengakses kunci individual serta nilai yang sesuai. Ada dua cara untuk melakukan ini:
- Mengiterasi hanya key
- Menggunakan metode `items()` untuk mendapatkan pasangan key-value.

In [11]:
# Membuat kamus bernama person
person = {"name": "Mahdy", "country": "Indonesia", "telephone": 1178}

# Mengiterasi kamus menggunakan for-loop
print('key', ':', 'value')
for key in person:
    print(key, ':', person[key])

print("\n")

# Menggunakan metode items() untuk iterasi
print('key', ':', 'value')
for key_value in person.items():
    # key_value[0] adalah kunci, dan key_value[1] adalah nilai
    print(key_value[0], key_value[1])

key : value
name : Mahdy
country : Indonesia
telephone : 1178


key : value
name Mahdy
country Indonesia
telephone 1178


Dalam loop pertama, kita hanya mengiterasi key dari dictionary person. Dengan `for key in person`, kita dapat mengakses setiap key, dan untuk mendapatkan value terkait, kita menggunakan `person[key]`

Pada loop kedua, kita menggunakan metode `items()` yang mengembalikan setiap pasangan key-value sebagai tuple. Di sini, `key_value[0]` adalah key dan `key_value[1]` adalah value. Ini membuatnya lebih mudah untuk mengakses pasangan key-value secara bersamaan.

## Menemukan Panjang Dictionary
Untuk mengetahui jumlah item dalam sebuah dictionary, kita dapat menggunakan fungsi `len()`. Fungsi ini akan mengembalikan jumlah key (dan value) yang ada dalam dictionary.

In [12]:
# Membuat kamus bernama person
person = {"name": "Mahdy", "country": "Indonesia", "telephone": 1178}

# Menghitung jumlah kunci dalam kamus
print(len(person))  # Output: 3

3


## Menetapkan Nilai Default ke Key pada Dictionary

Dengan menggunakan metode `setdefault()`, kita dapat menetapkan bukau default untuk sebuah key dalam dictionary. Jika key tersebut tidak ada, maka key akan ditambahkan ke dalam dictionary dengan value default yang ditentukan. Jika tidak ada value yang disebutkan, `None` akan menjadi nilai default.

Jika key sudah ada, metode ini akan mengembalikan nilai dari key tersebut tanpa mengubahnya.

In [13]:
# Membuat kamus bernama person_details
person_details = {"name": "Mahdy", "country": "Indonesia", "telephone": 1178}

# Menetapkan nilai default jika kunci tidak ada
person_details.setdefault('state', 'Singapore')

# Kunci tidak ada dan nilai tidak disebutkan. Defaultnya None
person_details.setdefault("zip")

# Kunci sudah ada dan nilai disebutkan. Tidak mengubah nilai
person_details.setdefault('country', 'Canada')

# Menampilkan kamus
for key, value in person_details.items():
    print(key, ':', value)


name : Mahdy
country : Indonesia
telephone : 1178
state : Singapore
zip : None


Dalam contoh di atas, kita mulai dengan dictionary `person_details` yang memiliki beberapa informasi. Ketika kita menggunakan `setdefault('state', 'Texas')`, key `state` ditambahkan dengan nilai `Texas` karena key tersebut tidak ada dalam dictionary sebelumnya. Pada pemanggilan `setdefault("zip")`, key `zip` ditambahkan ke dictionary dengan nilai default `None` karena tidak ada nilai yang diberikan. Ketika kita menggunakan `setdefault('country', 'Canada')`, karena key `country` sudah ada, nilai tetap `Indonesia` dan tidak ada perubahan yang terjadi.

## Memodifikasi Nilai Key dalam Dictionary
Kita dapat memodifikasi nilai dari key yang sudah ada dalam Dictionary dengan dua cara berikut:
- Menggunakan Nama Key: Kita dapat langsung menetapkan nilai baru dengan menggunakan nama key yang ada.
- Menggunakan Metode `update()`: Kita dapat menggunakan metode `update()` dengan memberikan pasangan key-value untuk mengubah nilai.

In [15]:
# Membuat kamus bernama person
person = {"name": "Mahdy", "country": "Indonesia"}

# Memperbarui nama negara
person["country"] = "Singapore"
# Menampilkan negara yang diperbarui
print(person['country'])  # Output: Singapore

# Memperbarui nama negara menggunakan metode update()
person.update({"country": "Malaysia"})
# Menampilkan negara yang diperbarui
print(person['country'])  # Output: Malaysia

Singapore
Malaysia


Dalam contoh di atas, kita mulai dengan dictionary person yang memiliki dua key: `name` dan `country`. Pertama, kita memperbarui nilai dari key `country` menjadi `Indonesia` dengan cara langsung menetapkan nilai baru menggunakan person["country"] = "Indonesia". Kemudian, kita mencetak nilai yang diperbarui. Selanjutnya, kita menggunakan metode update() untuk mengubah nilai key `country` menjadi `Malaysia`. Metode ini memudahkan kita untuk memperbarui nilai dengan memberikan pasangan key-value.

## Menghapus Item dari Dictionary
Ada beberapa metode untuk menghapus item dari dictionary. Baik itu untuk menghapus item tunggal, item terakhir yang dimasukkan, atau bahkan untuk menghapus seluruh dictionary, Anda dapat memilih metode yang sesuai.


|Metode|Deskripsi|
|---|---|
|pop(key[,d])|Mengembalikan dan menghapus item dengan kunci yangdiberikan dan mengembalikan nilainya. Jika kunci tidak ditemukan, akan menghasilkan KeyError.|
|popitem()|Mengembalikan dan menghapus item terakhir yang dimasukkan ke dalam dictionary. Jika dictionary kosong, akan menghasilkan KeyError.|
|del key|Keyword del akan menghapus item dengan kunci yang diberikan.|
|clear()|Menghapus semua item dari dictionary. Kamus menjadi kosong.|
|del dict_name|Menghapus seluruh dictionary.|


In [16]:
# Membuat kamus bernama person
person = {'name': 'Mahdy', 'country': 'Indonesia', 'telephone': 2834, 'weight': 58, 'height': 6}

# Menghapus item terakhir yang dimasukkan dari kamus
deleted_item = person.popitem()
print(deleted_item)  # Output: ('height', 6)
# Menampilkan kamus yang diperbarui
print(person)  # Output: {'name': 'Mahdy', 'country': 'Indonesia', 'telephone': 2834, 'weight': 58}

# Menghapus kunci 'telephone' dari kamus
deleted_item = person.pop('telephone')
print(deleted_item)  # Output: 2834
# Menampilkan kamus yang diperbarui
print(person)  # Output: {'name': 'Mahdy', 'country': 'Indonesia', 'weight': 58}

# Menghapus kunci 'weight'
del person['weight']
# Menampilkan kamus yang diperbarui
print(person)  # Output: {'name': 'Mahdy', 'country': 'Indonesia'}

# Menghapus semua item (kunci-nilai) dari kamus
person.clear()
# Menampilkan kamus yang diperbarui
print(person)  # Output: {}

# Menghapus seluruh kamus
del person

('height', 6)
{'name': 'Mahdy', 'country': 'Indonesia', 'telephone': 2834, 'weight': 58}
2834
{'name': 'Mahdy', 'country': 'Indonesia', 'weight': 58}
{'name': 'Mahdy', 'country': 'Indonesia'}
{}


## Memeriksa Keberadaan Kunci dalam Dictionary
Untuk memeriksa apakah kunci tertentu ada dalam sebuah kamus, kita dapat menggunakan metode keys() dan operator in. Dengan cara ini, kita dapat memeriksa apakah kunci tersebut ada dalam daftar kunci yang dikembalikan oleh metode keys().

In [17]:
# Membuat kamus bernama person
person = {'name': 'Mahdy', 'country': 'Indonesia', 'telephone': 628234, 'weight': 50, 'height': 6}

# Mendapatkan daftar kunci dan memeriksa apakah kunci 'country' ada
key_name = 'country'
if key_name in person.keys():
    print("country name is", person[key_name])
else:
    print("Key not found")


country name is Indonesia


## Menggabungkan Dua Dictionary
Kita dapat menambahkan dua dictionary menggunakan metode update() atau dengan menggunakan operator unpacking **

### Menggunakan Metode `update()`
Metode ini memungkinkan kita untuk menyalin dictionary kedua ke dalam dictionary pertama. Jika ada key yang sama, nilai pada dictionary pertama akan diperbarui dengan nilai dari dictionary kedua.

In [19]:
dict1 = {'Mahdy': 25, 'Arun': 80, 'Meena': 55}
dict2 = {'Kelvin': 68, 'Harry': 50, 'Om': 66}

# Menyalin kamus kedua ke dalam kamus pertama
dict1.update(dict2)

# Menampilkan kamus yang diperbarui
print(dict1)  
# Output: {'Mahdy': 25, 'Arun': 80, 'Meena': 55, 'Kelvin': 68, 'Harry': 50, 'Om': 66}


{'Mahdy': 25, 'Arun': 80, 'Meena': 55, 'Kelvin': 68, 'Harry': 50, 'Om': 66}


### Menggunakan Unpacking `**kwargs`
Kita juga dapat menggabungkan beberapa dictionary dengan menggunakan operator unpacking `**`. Ini memungkinkan kita untuk menambahkan beberapa dictionary sekaligus ke dalam satu dictionary dalam satu pernyataan.

In [20]:
student_dict1 = {'Mahdy': 1, 'Arun': 2}
student_dict2 = {'Farhan': 5, 'Om': 6}
student_dict3 = {'Nancy': 7, 'Priya': 9}

# Menggabungkan tiga kamus
student_dict = {**student_dict1, **student_dict2, **student_dict3}

# Menampilkan kamus gabungan
print(student_dict)  
# Output: {'Mahdy': 1, 'Arun': 2, 'Farhan': 5, 'Om': 6, 'Nancy': 7, 'Priya': 9}


{'Mahdy': 1, 'Arun': 2, 'Farhan': 5, 'Om': 6, 'Nancy': 7, 'Priya': 9}


### Menambahkan Beberapa Dictionary ke dalam Dictionary Tunggal
Dalam contoh berikut, kita akan membuat dictionary terpisah untuk setiap siswa, dan di akhir, kita akan menambahkan setiap siswa ke dalam dictionary class_six. Setiap siswa akan menjadi kunci dalam dictionary class_six.

In [21]:
# Kamus untuk menyimpan data masing-masing siswa
Mahdy = {'Name': 'Mahdy', 'State': 'Indonesia', 'City': 'Surabaya'}
Gigih = {'Name': 'Gigih', 'State': 'Indonesia', 'City': 'Malang'}
Kevin = {'Name': 'Kevin', 'State': 'Indoesia', 'City': 'Palangkaraya'}

# Kamus luar untuk menyimpan semua kamus siswa (nested dictionaries)
class_six = {'student1': Mahdy, 'student2': Gigih, 'student3': Kevin}

# Mendapatkan nama dan nilai siswa3
print("Student 3 name:", class_six['student3']['Name'])  # Output: Kelvin
print("Student 3 marks:", class_six['student3']['City'])  # Output: 85

# Mengiterasi kamus luar
print("\nClass details\n")
for key, value in class_six.items():
    # Mengiterasi melalui kamus nested
    # Menampilkan data setiap siswa
    print(key)
    for nested_key, nested_value in value.items():
        print(nested_key, ':', nested_value)
    print('\n')

Student 3 name: Kevin
Student 3 marks: Palangkaraya

Class details

student1
Name : Mahdy
State : Indonesia
City : Surabaya


student2
Name : Gigih
State : Indonesia
City : Malang


student3
Name : Kevin
State : Indoesia
City : Palangkaraya




## Pemahaman Dictionary (Dictionary Comprehension)

Pemahaman Dictionary adalah salah satu cara untuk membuat dictionary di Python, di mana nilai-nilai dari pasangan kunci-nilai dihasilkan dalam `loop for`, dan kita dapat menyaring item yang akan ditambahkan ke dalam dictionary dengan kondisi `if opsional`.

In [22]:
# Menghitung kuadrat dari setiap angka genap dari sebuah list dan menyimpannya dalam kamus
numbers = [1, 3, 5, 2, 8]
even_squares = {x: x ** 2 for x in numbers if x % 2 == 0}
print(even_squares)  # Output: {2: 4, 8: 64}

{2: 4, 8: 64}


Dalam contoh di atas, kita memiliki daftar numbers. Dengan menggunakan pemahaman dictionary, kita membuat dictionary even_squares yang berisi angka genap dari daftar sebagai kunci dan kuadratnya sebagai nilai. Hanya angka yang memenuhi syarat (yaitu, angka genap) yang ditambahkan ke dalam dictionary, sehingga hasilnya adalah {2: 4, 8: 64}.

### Menggunakan Dua Iterables untuk Membuat Dictionary
Kita juga dapat menggunakan dua iterable yang berbeda untuk kunci dan nilai dan menggabungkannya menggunakan zip() di dalam loop for untuk membuat dictionary.

In [ ]:
telephone_book = [1178, 4020, 5786]
persons = ['Mahdy', 'Emma', 'Kelvin']

# Membuat kamus buku telepons
telephone_Directory = {key: value for key, value in zip(persons, telephone_book)}
print(telephone_Directory)  # Output: {'Mahdy': 1178, 'Emma': 4020, 'Kelvin': 5786}


{'Mahdy': 1178, 'Emma': 4020, 'Kelvin': 5786}


Dalam contoh ini, kita memiliki dua daftar: persons yang berisi nama-nama dan telephone_book yang berisi nomor telepon. Dengan menggunakan zip(persons, telephone_book), kita menggabungkan dua daftar tersebut menjadi pasangan kunci-nilai, di mana setiap nama berfungsi sebagai kunci dan nomor telepon sebagai nilai. Hasilnya adalah kamus telephone_Directory yang menyimpan informasi buku telepon dengan format {'Mahdy': 1178, 'Emma': 4020, 'Kelvin': 5786}.